# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Black Duck Security Action allows you to integrate Static Analysis Security Testing (SAST) and Software Composition Analysis (SCA) into your CI/CD pipelines.
# For more information about configuring your workflow,
# read our documentation at https://github.com/blackduck-inc/black-duck-security-scan
name: Black Duck Security Scan
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]
  workflow_dispatch:
  
# env:
#   GIT_ACCESS_TOKEN: ${{ secrets.BOT_SECRET_KEY }}
jobs:
  blackduck-scan:
    runs-on: ubuntu-22.04 #포트포워딩으로 Black Duck 서버를 사용할 경우
    steps:
      - uses: actions/checkout@v4
      # - run: git config --global url.https://$GIT_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
    
      - name: Black Duck SCA Scan
        id: black-duck-scan
        uses: blackduck-inc/black-duck-security-scan@v2

        with:
          include_diagnostics: true
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          blackducksca_prcomment_enabled: true
          github_token: ${{ secrets.GH_TOKEN }}
          blackducksca_fixpr_enabled: true
          blackducksca_waitForScan: true
          mark_build_status: failure
          detect_args: |
            --detect.excluded.detector.types=GIT
            --blackduck.trust.cert=true
#TEST
#--detect.blackduck.rapid.compare.mode=BOM_COMPARE_STRICT
#--detect.policy.check.fail.on.severities=CRITICAL
