# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Black Duck Security Action allows you to integrate Static Analysis Security Testing (SAST) and Software Composition Analysis (SCA) into your CI/CD pipelines.
# For more information about configuring your workflow,
# read our documentation at https://github.com/blackduck-inc/black-duck-security-scan
name: Black Duck Security Scan
on:
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  workflow_dispatch: {}
env:
  GIT_ACCESS_TOKEN: ${{ secrets.BOT_SECRET_KEY }}
jobs:
  blackduck-scan:
    runs-on: ubuntu-22.04 #포트포워딩으로 Black Duck 서버를 사용할 경우
    steps:
      - uses: actions/checkout@v4
      - run: git config --global url.https://$GIT_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
                
      - name: Run Black Duck Scan
        id: black-duck-sca-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        # env:
        #   DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackducksca_prcomment_enabled: true
          blackducksca.automation.prComment: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          detect_search_depth: 10
          blackducksca_scan_full: false
          detect_args: |
            --detect.blackduck.scan.mode=RAPID
            --detect.excluded.detector.types=GIT
            --detect.project.name=Webgoat
            --detect.project.version.name=Action_Test
            --blackduck.trust.cert=true
            --detect.accuracy.required=NONE
            --detect.timeout=5000
#--detect.policy.check.fail.on.severities=CRITICAL
