name: Black Duck SCAN
on:
  pull_request:
    branches:
      - main
jobs:
  security:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    #- name: Build webgoat with maven
      #run: ./mvnw install-DskipTests
      #run: ./mvnw install -DskipTests
   
   #- name: Create certificate
      #run: cat <<< "${{secrets.BASE_64_CERTIFICATE_CONTENT}}" > my-cert.pem
      
    - name: Run Synopsys Detect
      uses: seolyekwon/detect-action@main
      #env:
          #NODE_EXTRA_CA_CERTS: .github/workflows/crt/hub-webserver.pem
          #NODE_EXTRA_CA_CERTS: ./my-cert.pem
      with:
          scan-mode: INTELLIGENT
          github-token: ${{ secrets.GIT_TOKEN }}
          detect-trust-cert: true
          detect-version: 7.9.0
          #blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-url: ${{ secrets.BLACKDUCK_EXT_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
