name: Black Duck Intelligent Scan 

on:
  pull_request:
    branches:
      - main
  #schedule:
   # - cron: '5 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up JDK 11 in runtime environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Run Synopsys Detect
      - name: Run Synopsys Detect
        uses: synopsys-sig/synopsys-action@v1.5.0
        # This server does not require a local CA Cert
        #env:
        #  NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
        # Enable diagnostic mode
        env:
          DETECT_DIAGNOSTIC: true
          DETECT_DETECTOR_SEARCH_DEPTH: 10
          DETECT_PROJECT_NAME: WebGoat-v800
          DETECT_PROJECT_DESCRIPTION: WebGoat-Git
          DETECT_PROJECT_USER_GROUPS: Black Duck Project Groups
          DETECT_PROJECT_VERSION_NAME: v8.0.0
          DETECT_PROJECT_GROUP_NAME: SoftFlow
          #DETECT_DIAGNOSTIC_EXTENDED: true
        with:
            scan-mode: INTELLIGENT
            github-token: ${{ secrets.GIT_TOKEN }}
            detect-version: 9.0.0
            blackduck-url: ${{ secrets.BLACKDUCK_URL }}
            blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
