name: Black Duck Intelligent Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: write-all
    
jobs:
  build:
  # The type of runner that the job will run    
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can acces
      - uses: actions/checkout@HEAD
      # set up JDK 11 in runtime environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        #uses: actions/setup-java@v2
        with:
          java-version: '17'
          #java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: ./mvnw clean install -DskipTest
        # Run Synopsys Detect
      - name: Checkout
        uses: actions/checkout@v3
      - name: Synopsys Action
        #uses: synopsys-sig/synopsys-action@v1.0.0
        uses: synopsys-sig/synopsys-action@v1.5.0
        env:
          NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
          DETECT_DIAGNOSTIC: true
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          #blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }} #blackduck-api-token is Unexpected input
          # Optional parameter. By default, pushes will initiate a full "intell
          # will initiate a rapid scan.
          blackduck_scan_full: true
          # Passing false will disable fix pull request creation
          blackduck_automation_fixpr: false
          # Optional parameter. The values could be. ALL|NONE|BLOCKER|CRITICAL
          # Single parameter
          #blackduck_scan_failure_severities: "[\"CRITICAL\"]" #Error: Workflow failed! Invalid value for blackduck_scan_failure_severities
          # multiple parameters
          # blackduck_scan_failure_severities: "[\"BLOCKER\", \"CRITICAL\", \"]
